apiVersion: v1
kind: List
items:
# ---------------------------------------------------------
# CONTROL PLANE (MASTER)
# ---------------------------------------------------------
- apiVersion: v1
  kind: Node
  metadata:
    name: k3s-master
    labels:
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: k3s-master
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
      node.kubernetes.io/instance-type: k3s
  spec:
    podCIDR: 10.42.0.0/24
    providerID: k3s://k3s-master
  status:
    allocatable:
      cpu: "12"
      memory: 16374520Ki # ~16GB RAM
      pods: "110"

# ---------------------------------------------------------
# WORKER NODE 01
# ---------------------------------------------------------
- apiVersion: v1
  kind: Node
  metadata:
    name: k3s-worker-01
    labels:
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: k3s-worker-01
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: k3s
  spec:
    podCIDR: 10.42.4.0/24
    providerID: k3s://k3s-worker-01
  status:
    allocatable:
      cpu: "12"
      memory: 8129276Ki # ~8GB RAM
      pods: "110"

# ---------------------------------------------------------
# WORKER NODE 02
# ---------------------------------------------------------
- apiVersion: v1
  kind: Node
  metadata:
    name: k3s-worker-02
    labels:
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: k3s-worker-02
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: k3s
  spec:
    podCIDR: 10.42.1.0/24
    providerID: k3s://k3s-worker-02
  status:
    allocatable:
      cpu: "12"
      memory: 8129276Ki # ~8GB RAM
      pods: "110"